---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis-operator
  name: redis-operator
spec:
  selector:
    matchLabels:
      app: redis-operator
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
      labels:
        app: redis-operator
    spec:
      serviceAccountName: redis-operator
      containers:
        - name: redis-operator
          image: amaiz/redis-operator:v0.2.1
          args:
            - --zap-time-encoding
            - iso8601
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: redis-operator
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /tmp
              name: tmpfs
      securityContext:
        runAsUser: 7777777
        runAsGroup: 7777777
        fsGroup: 7777777
        runAsNonRoot: true
      volumes:
        - emptyDir: {}
          name: tmpfs
