apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
spec:
  strategy: allInOne
  allInOne:
    options:
      query:
        base-path: /jaeger
  storage:
    type: memory
    options:
      memory:
        max-traces: 1000
  ingress:
    enabled: false
