apiVersion: batch/v1
kind: Job
metadata:
  name: veidemann-db-initializer
  labels:
    app.kubernetes.io/name: veidemann-db-initializer
    app.kubernetes.io/component: db-initializer
spec:
  template:
    metadata:
      name: veidemann-db-initializer
      labels:
        app.kubernetes.io/name: veidemann-db-initializer
        app.kubernetes.io/component: db-initializer
    spec:
      restartPolicy: Never
      containers:
        - name: veidemann-db-initializer
          image: norsknettarkiv/veidemann-db-initializer:0.4.12
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: veidemann-rethinkdb-env
                optional: false
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DB_HOST
              value: "rethinkdb-proxy"
            - name: DB_PORT
              value: "28015"
            - name: DB_NAME
              value: "veidemann"
