apiVersion: v1
kind: Pod
metadata:
  name: veidemann-util-pod
  namespace: veidemann
spec:
  volumes:
    - name: warcs
      persistentVolumeClaim:
        claimName: veidemann-warcs
    - name: backup
      persistentVolumeClaim:
        claimName: veidemann-backup
  containers:
    - name: warc-inspector-image
      image: norsknettarkiv/veidemann-warc-inspector-image:1.2.0
      args:
        - "sh"
        - "-c"
        - "trap : TERM INT; (while true; do sleep 1000; done) & wait"
      volumeMounts:
        - mountPath: "/veidemann/backup"
          name: backup
        - mountPath: "/veidemann/warcs"
          name: warcs
          subPath: warcs
        - mountPath: "/veidemann/invalidwarcs"
          name: warcs
          subPath: invalidwarcs
        - mountPath: "/veidemann/validwarcs"
          name: warcs
          subPath: validwarcs

