all: veidemann-commons veidemann-rethinkdbadapter veidemann-frontier

veidemann-commons:
	git clone https://github.com/nlnwa/veidemann-commons.git

veidemann-rethinkdbadapter:
	git clone https://github.com/nlnwa/veidemann-rethinkdbadapter.git

veidemann-frontier:
	git clone https://github.com/nlnwa/veidemann-frontier.git

