apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rethinkdb-cluster
  labels:
    app.kubernetes.io/name: rethinkdb
    app.kubernetes.io/component: cluster
spec:
  serviceName: rethinkdb-cluster
  selector:
    matchLabels:
      app.kubernetes.io/name: rethinkdb
      app.kubernetes.io/component: cluster
  template:
    metadata:
      name: rethinkdb-cluster
      labels:
        app.kubernetes.io/name: rethinkdb
        app.kubernetes.io/component: cluster
    spec:
      priorityClassName: rethinkdb-priority
      serviceAccountName: rethinkdb
      containers:
        - name: rethinkdb-cluster
          image: codylundquist/helm-rethinkdb-cluster:0.1.0
          ports:
            - name: cluster
              containerPort: 29015
          args:
            - --directory
            - /data/db
            - --bind
            - $(POD_IP)
            - --no-http-admin
            - --no-update-check
          volumeMounts:
            - name: datadir
              mountPath: /data/db
          env:
            - name: RETHINK_CLUSTER_SERVICE
              value: $(RETHINK_CLUSTER_SERVICE_NAME)
            - name: RETHINKDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rethinkdb
                  key: rethinkdb-password
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          livenessProbe:
            exec:
              command:
                - /rethinkdb-probe
            initialDelaySeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - /rethinkdb-probe
            initialDelaySeconds: 10
            timeoutSeconds: 5
      volumes:
        - name: datadir
          emptyDir: {}
