{
 "title": "Veidemann / RethinkDB",
 "description": "Dashboard for Prometheus collected RethinkDB stats",
 "tags": [
  "rethinkdb",
  "veidemann"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Client connections",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rethinkdb_cluster_client_connections)"
    }
   ]
  },
  {
   "title": "Cluster clients active",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rethinkdb_cluster_clients_active)"
    }
   ]
  },
  {
   "title": "Server client connections",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rethinkdb_server_client_connections)"
    }
   ]
  },
  {
   "title": "Server client active connections",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rethinkdb_server_clients_active)"
    }
   ]
  },
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Queries/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rethinkdb_cluster_queries_per_sec)"
    }
   ]
  },
  {
   "title": "Read docs/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rethinkdb_cluster_read_docs_per_sec)"
    }
   ]
  },
  {
   "title": "Written docs/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rethinkdb_cluster_written_docs_per_sec)"
    }
   ]
  },
  {
   "title": "Total servers",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "rethinkdb_cluster_servers_total"
    }
   ]
  },
  {
   "title": "Total tables",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "rethinkdb_cluster_tables_total" }
   ]
  },
  {
   "title": "Total replicas",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "rethinkdb_cluster_replicas_total"
    }
   ]
  },
  {
   "title": "Total server errors",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "rethinkdb_cluster_server_errors_total"
    }
   ]
  },
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Server io/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rethinkdb_server_queries_per_sec)",
     "legendFormat": "Queries/sec"
    },
    {
     "expr": "sum(rethinkdb_server_read_docs_per_sec)",
     "legendFormat": "Read/sec"
    },
    {
     "expr": "sum(rethinkdb_server_written_docs_per_sec)",
     "legendFormat": "Write/sec"
    }
   ]
  },
  {
   "title": "Queries total",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 24 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rethinkdb_server_queries_total)"
    }
   ]
  },
  {
   "title": "Read docs total",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 24 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rethinkdb_server_read_docs_total)"
    }
   ]
  },
  {
   "title": "Written docs total",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 24 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rethinkdb_server_written_docs_total)"
    }
   ]
  },
  { "title": "Tables", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Table disk usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (server)(rethinkdb_table_server_disk_data_bytes)"
    }
   ]
  },
  {
   "title": "Table cache usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (server)(rethinkdb_table_server_cache_in_use_bytes)"
    }
   ]
  },
  {
   "title": "Table metadata usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (server) (rethinkdb_table_server_disk_metadata_bytes)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Table prealocated usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (server) (rethinkdb_table_server_disk_preallocated_bytes)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Table garbage usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (server) (rethinkdb_table_server_disk_garbage_bytes)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Read Bytes/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rethinkdb_table_server_disk_read_bytes_per_sec)"
    }
   ]
  },
  {
   "title": "Written Bytes/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 39 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rethinkdb_table_server_disk_written_bytes_per_sec)"
    }
   ]
  },
  {
   "title": "Read Docs/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(rethinkdb_table_read_docs_per_sec)",
     "legendFormat": "Reads"
    }
   ]
  },
  {
   "title": "Written Docs/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 39 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "sum(rethinkdb_table_written_docs_per_sec)"
    }
   ]
  },
  {
   "title": "Server Read Bytes/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rethinkdb_table_server_read_docs_per_sec)"
    }
   ]
  },
  {
   "title": "Server Written Bytes/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rethinkdb_table_server_written_docs_per_sec)"
    }
   ]
  }
 ]
}