apiVersion: apps/v1
kind: Deployment
metadata:
  name: veidemann-scopeservice
  labels:
    app.kubernetes.io/name: veidemann-scopeservice
    app.kubernetes.io/component: scopeservice
  annotations:
    sidecar.jaegertracing.io/inject: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: veidemann-scopeservice
      app.kubernetes.io/component: scopeservice
  template:
    metadata:
      labels:
        app.kubernetes.io/name: veidemann-scopeservice
        app.kubernetes.io/component: scopeservice
      annotations:
        config.linkerd.io/skip-inbound-ports: "9153"
        config.linkerd.io/skip-outbound-ports: "14250"
        linkerd.io/inject: enabled
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: veidemann-scopeservice
          image: ghcr.io/nlnwa/veidemann-scopeservice:0.1.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: grpc
              containerPort: 8080
              protocol: TCP
            - name: http-metrics
              containerPort: 9153
              protocol: TCP
          env:
            - name: PORT
              value: "8080"
            - name: JAEGER_SERVICE_NAME
              value: veidemann-robotsevaluator-service
            - name: JAEGER_AGENT_HOST
              value: localhost
            - name: JAEGER_AGENT_PORT
              value: "6831"
            - name: JAEGER_SAMPLER_TYPE
              value: remote
            - name: JAEGER_SAMPLER_PARAM
              value: "0.1"
            - name: JAVA_TOOL_OPTIONS
              value: -Dfile.encoding=UTF-8
            - name: JAEGER_PROPAGATION
              value: jaeger,b3
            - name: LOG_LEVEL
              value: debug
