apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: rethinkdb-proxy
  labels:
    app.kubernetes.io/name: rethinkdb
    app.kubernetes.io/component: proxy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: rethinkdb
      app.kubernetes.io/component: proxy
  template:
    metadata:
      name: rethinkdb-proxy
      labels:
        app.kubernetes.io/name: rethinkdb
        app.kubernetes.io/component: proxy
      annotations:
        linkerd.io/inject: enabled
        config.linkerd.io/opaque-ports: "28015"
        config.linkerd.io/skip-inbound-ports: "29015"
        config.linkerd.io/skip-outbound-ports: "29015"
    spec:
      priorityClassName: rethinkdb-priority
      serviceAccountName: rethinkdb
      containers:
        - name: rethinkdb-proxy
          image: codylundquist/helm-rethinkdb-cluster:0.1.0
          ports:
            - name: cluster
              containerPort: 29015
            - name: driver
              containerPort: 28015
          args:
            - --bind
            - $(POD_IP)
            - --no-update-check
            - --no-http-admin
          env:
            - name: PROXY
              value: "true"
            - name: RETHINK_CLUSTER_SERVICE
              value: $(RETHINK_CLUSTER_SERVICE_NAME)
            - name: RETHINKDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  optional: false
                  name: rethinkdb-env
                  key: DB_PASSWORD
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          startupProbe:
            exec:
              command:
                - /rethinkdb-probe
            failureThreshold: 10
          livenessProbe:
            exec:
              command:
                - /rethinkdb-probe
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - /rethinkdb-probe
            timeoutSeconds: 5
