apiVersion: apps/v1
kind: Deployment
metadata:
  name: veidemann-cache-balancer
  labels:
    app.kubernetes.io/name: veidemann-cache
    app.kubernetes.io/component: cache-balancer
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: veidemann-cache
      app.kubernetes.io/component: cache-balancer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: veidemann-cache
        app.kubernetes.io/component: cache-balancer
    spec:
      serviceAccountName: veidemann-cache
      containers:
        - name: veidemann-cache-balancer
          image: norsknettarkiv/veidemann-cache:0.2.3
          args:
            - squid
            - -b
          env:
            - name: DNS_SERVERS
              value: veidemann-dns-resolver
            - name: SERVICE_NAME
              value: veidemann-cache
          ports:
            - containerPort: 3128
              name: http
              protocol: TCP
        - name: veidemann-cache-exporter
          image: boynux/squid-exporter:v1.1
          imagePullPolicy: IfNotPresent
          args:
            - -listen
            - 0.0.0.0:9301
          ports:
            - containerPort: 9301
              name: http-metrics
              protocol: TCP
